spring:
  datasource:
    url: jdbc:mysql://localhost:3306/traffic?serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      username: useb
      password: UsebUseb007!
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
logging:
  level:
    org.springframework.web.client: debug
    org.hibernate.type: trace
